### ISSUE TITLE
支持复制请求url

### ISSUE THREAD

**Issue by yhan219** [huzunrong/RESTKit-Doc#1]
- 支持复制完整url（含端口等）
- 支持复制映射（不含端口等）
- 复制链接时支持复制参数

这几个功能是RestfulToolKit上比较好用的功能，直接在请求方法上右键就能使用，希望能支持下，感谢

右键截图如下
![image](https://user-images.githubusercontent.com/12593660/142136127-2eb6936a-4dde-4937-9812-7ddcb4810db1.png)

**Comment by huzunrong** [comment]
可以考虑，用得少就去掉了，什么情景需要经常这样操作呢？

**Comment by huzunrong** [comment]
可以考虑，但是用的少，复制的参数是随机生成的，什么情景需要经常这样操作呢？

**Comment by yhan219** [comment]
主要是临时调试下接口的时候比较有用。或者可以考虑下点击到方法或者mapping的时候，右边RestKit窗口能自动选中到当前点击的mapping，这样更方便点。比如可以在以下两个其中一个地方加个跳转，点击Kit窗口自动选中到url

![image](https://user-images.githubusercontent.com/12593660/142554043-cdae3025-e0d2-4d18-949f-051903df80c0.png)

<img width="378" alt="2021-11-19 101705" src="https://user-images.githubusercontent.com/12593660/142553982-b49be2b9-d89c-40fb-ae5d-b6662762cd31.png">

**Comment by huzunrong** [comment]
了解，目前在Mapping方法的上下文菜单中可以跳转到RESTKit窗口，文档中有描述，下个版本对这块优化。

**Comment by yhan219** [comment]
感谢，没注意看。想要的就是这个功能
